USE library;
# 创建BOOKS
/*
CREATE TABLE BOOKS(
BOOK_ID VARCHAR(20) PRIMARY KEY,
BNAME VARCHAR(40),
 publisher VARCHAR(40),
 AUTHOR VARCHAR(40),
 CDATE DATE ,
 CLASS VARCHAR(30),
 FLAG BOOL
);

# 创建USERS
CREATE TABLE USERS(
SNAME VARCHAR(40) NOT NULL,
STU_ID VARCHAR(40) PRIMARY KEY ,
sex VARCHAR(2)  NOT NULL
);


# 创建BORROW_RECORD`books`
CREATE TABLE BORROW_RECORD(
R_ID INT PRIMARY KEY AUTO_INCREMENT,
STU_ID VARCHAR(40),
BOOK_ID VARCHAR(40),
BDATE DATE,

FOREIGN KEY(STU_ID) REFERENCES USERS(STU_ID),
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

# 创建SEND_RECORD
CREATE TABLE SEND_RECORD(
S_ID INT PRIMARY KEY AUTO_INCREMENT,
STU_ID VARCHAR(40),
BOOK_ID VARCHAR(40),
BDATE DATE,

FOREIGN KEY(STU_ID) REFERENCES USERS(STU_ID),
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
`borrow_record`
# 创建在借书籍表`book_class`
CREATE TABLE borrowed_book(
BOOK_ID VARCHAR(20) PRIMARY KEY,
STU_ID  VARCHAR(40) ,
FOREIGN KEY(STU_ID) REFERENCES USERS(STU_ID),
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);*/
# 创建管理员
/*
create Table admin (
ADM_ID VARCHAR(40) primary key,
ADM_NAME VARCHAR(20)
)
*/

/*
create table book_class (
	class_name Varchar(20),
	class_id varchar(20) primary key
)*/
/*
ALTER TABLE book_class ADD INDEX idx_class(class_name);

ALTER TABLE books
ADD CONSTRAINT CLASS
FOREIGN KEY   (CLASS)
REFERENCES book_class(class_name);*/
/*
SELECT a.BNAME, publisher,AUTHOR,CDATE,CLASS ,counter FROM 
(SELECT DISTINCT BNAME, publisher,AUTHOR,CDATE,CLASS FROM  books WHERE GROUP BY BOOK_ID) as a,
(SELECT BNAME,COUNT(BOOK_ID) as counter FROM books WHERE FLAG = 1  GROUP BY BNAME) as b
WHERE a.BNAME = b.BNAME*/




#ELETE FROM send_record WHERE BOOK_ID = "1003";

SELECT bb.BOOK_ID,BNAME,bb.STU_ID,SNAME FROM borrowed_book AS bb,users AS us,books AS bs
WHERE bb.`BOOK_ID` =  bs.`BOOK_ID` AND bb.`STU_ID` = us.`STU_ID`


















